site_name: "Kaspresso"
repo_url: https://github.com/KasperskyLab/Kaspresso
repo_name: Kaspresso
edit_uri: tree/main/docs/content
docs_dir: 'docs'
remote_branch: gh-pages
language: en

theme:
  favicon: kaspresso.png
  logo: kaspresso.png
  icon:
    logo: fontawesome/brands/android

  palette:
    - scheme: default
      primary: teal
      accent: light blue
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
    - scheme: slate
      primary: black
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode


  name: 'material'
#  custom_dir: ../mkdocs-material/material

  # 404 page
  static_templates:
    - ../mkdocs-material/material/404.html

  # Necessary for search to work properly
  include_search_page: false
  search_index_only: true

  # Default values, taken from mkdocs_theme.yml
  language: en
  font:
    text: Roboto
    code: Roboto Mono
 # favicon: assets/favicon.png

  features:
    - tabs
    - navigation.tabs
    - content.code.annotate
    - navigation.tabs.sticky
    - navigation.instant
    - navigation.tracking
    - navigation.top
    - search.suggest
    - search.highlight

nav:
  - Home:
    - About Kaspresso: index.md
    - Kaspresso in articles: Home/Kaspresso-in-articles.md
    - Kasspresso in videos: Home/Kaspresso-in-videos.md
    - Our users: Home/Kaspresso users.md
    - Breaking changes: Home/Breaking-changes.md
    - Contribution guide: Home/Contribution_guide.md
#  - Tutorial (old):
#    - Index: Tutorial/index.md
#    - Скачиваем проект и Android Studio: Tutorial/Android_studio.md
#    - Запуск первого теста: Tutorial/Running_the_first_test.md
#    - Ваш первый тест на Kaspresso: Tutorial/simple_test.md
#    - Тестирование за рамками приложения: Tutorial/off-screen_work.md
#    - Flaky safely. Сontinuously, compose.: Tutorial/Flaky safely.md
#    - Использование сценариев в Kaspresso: Tutorial/Kaspresso_scenario.md
#    - Выполнение adb-команд: Tutorial/adb_commands.md
#    - Взаимодействуем с Android вне приложения: Tutorial/Device.md
#    - Конфигурирование Kaspresso: Tutorial/Kaspresso_configurator.md
#    - Скриншот-тесты: Tutorial/Kaspresso_screenshots.md
#    - Использование Allure: Tutorial/Kaspresso_with_allure.md
  - Tutorial:
      - Введение: Tutorial/index.md
      - Скачиваем проект и Android studio: Tutorial/Download_Kaspresso_project_and_Android_studio.md
      - Запуск первого теста: Tutorial/Running_the_first_test.md
      - Пишем первый автотест с Kaspresso: Tutorial/Writing_simple_test.md
      - Выполнение adb-команд: Tutorial/Выполнение adb-команд.md
      - Выполнение adb-команд: Tutorial/Wii_sample_test.md
      - Выделение секций и шагов: Tutorial/Выделение секций и шагов.md
      - Вынесение дублирующихся шагов в Scenario: Tutorial/Вынесение дублирующихся шагов в Scenario.md
      - Тестирование за рамками приложения: Tutorial/Тестирование за рамками приложения.md
      - Работа с разрешениями и тестовыми Rules: Tutorial/Работа с разрешениями и тестовыми Rules.md
      - Работа с Android OS: Tutorial/Работа с Android OS.md
      - Скриншот-тесты: Tutorial/Скриншот-тесты.md
      - Flaky safety: Tutorial/Flaky safety.md
      - Работа с WebView: Tutorial/Работа с WebView.md
      - Конфигурирование Kaspresso: Tutorial/Конфигурирование Kaspresso.md
      - Использование Allure: Tutorial/Использование Allure.md
  - Wiki:
      - Introduction: Wiki/index.md
      - PageObject in Kaspresso: Wiki/Page_object_in_Kaspresso.md
      - Espresso as the basis: Wiki/Espresso_as_the_basis.md
      - Migrate from Espresso, Kakao or KAutomator: Wiki/Migrate_from_Espresso.md
      - Supported Android UI-elements: Wiki/Supported_Android_UI_elements.md
      - View matchers, actions and assertions: Wiki/Matchers_actions_assertions.md
      - Kautomator. Wrapper over UI Automator: Wiki/Kautomator-wrapper_over_UI_Automator.md
      - Executing adb commands: Wiki/Executing_adb_commands.md
      - Screenshot tests: Wiki/Screenshot_tests.md
      - Kaspresso configuration: Wiki/Kaspresso_configuration.md
      - Working with Android OS: Wiki/Working_with_Android_OS.md
      - Kaspresso with Robolectric: Wiki/Kaspresso_Robolectric.md
      - Kaspresso with Allure: Wiki/Kaspresso_Allure.md
      - E2e and Functional tests. All in one: Wiki/E2e_and_Functional_tests.md
      - Jetpack Compose in Kaspresso: Wiki/Jetpack_Compose.md
  - Issues:
    - Found an issue?: Issues/index.md
    - Storage issues: Issues/Storage_issue.md
#  - Wiki(old):
#      - Page object in Kaspresso: Wiki/Page object in Kaspresso.md
#      - Wrapper over Espresso: Wiki/01_Wrapper_over_Espresso.md
#      - Wrapper over UiAutomator: Wiki/02_Wrapper_over_UiAutomator.md
#      - Kaspresso configurator: Wiki/03_Kaspresso_configurator.md
#      - How to write autotests: Wiki/04_How_to_write_autotests.md
#      - Device: Wiki/05_Device.md
#      - AdbServer: Wiki/06_AdbServer.md
#      - DocLoc: Wiki/07_DocLoc.md
#      - Kaspresso Robolectric: Wiki/08_Kaspresso-Robolectric.md
#      - Kaspresso Allure: Wiki/09_Kaspresso-Allure.md
#      - Jetpack Compose: Wiki/10_Jetpack-Compose.md
#  - Documentation:
#    - Kaspresso docs: Documentation/kaspresso/index.md
#    - KAutomator docs: Documentation/kautomator/index.md
#    - ADB Server: Documentation/adb-server/index.md
#   Home/Kaspresso.md

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences

extra:
  alternate:
    - name: English
      link: /en/
      lang: en
    - name: Russian
      link: /ru/
      lang: ru
